### ISSUE TITLE
rastertopdf: DCT_DECODE unable to compress image stream for large stream in PCLm.

### ISSUE THREAD

**Issue by sahilarora535** [sahilarora535/cups-filters#3]
For streams with large size, i.e. large `width` and `height`, the `DCT_DECODE` compression for compressing the image fails. For instance, for [this 600dpi raster file](https://github.com/sahilarora535/raster-to-pclm/blob/master/raster-images/600dpi/onepage-a4-srgb-8-600dpi.pwg) and strip height = 32, the PCLm file is empty, whereas for strip height = 6 and below, we get the PCLm file successfully.

https://github.com/sahilarora535/cups-filters/blob/ccb47b24178fc454713fd7b1051d80c1389db81b/filter/rastertopdf.cpp#L690-L697

The reason can be that there is a limit on the dimensions of the image using `libjpeg`. `width` and `height` are of type `JDIMENSION` in `libjpeg`. See the following blob in `libjpeg` which defines the type `JDIMENSION`: 

https://github.com/LuaDist/libjpeg/blob/6c0fcb8ddee365e7abc4d332662b06900612e923/jmorecfg.h#L221-L232

**Comment by jberkenbilt** [comment]
It's hard for me to imagine that such a limit would be a factor in most cases. Even at 600 dpi and 17 inches wide, you're still less than 1/5 of the maximum image dimensions. I wonder if it could be some other issue. What would cause the pclm file to be empty? Is something not trapping errors properly? Maybe you should do a try/catch block around the contents of the block above and print the value of any exception for debugging. You can catch std::exception and print e.what(). Most of the examples in qpdf do this. Most likely some error condition will be exposed.

**Comment by sahilarora535** [comment]
@jberkenbilt Thanks a lot for the info. I figured out that the last strip may or may not have fixed height, and that was the problem. It has been fixed in commit https://github.com/sahilarora535/cups-filters/commit/c89d47a9e66d1cfcc6f20dd38936d4dfbb6afd60
